# Generated by Django 4.2.29 on 2026-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='current_diseases',
            field=models.TextField(blank=True, help_text='Current health conditions/diseases'),
        ),
    ]
