# Generated by Django 6.0.3 on 2026-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patientprofile_current_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(blank=True, default='Monday,Tuesday,Wednesday,Thursday,Friday', help_text='Available days (e.g., Monday,Tuesday,Wednesday,Thursday,Friday)', max_length=100),
        ),
    ]
