# Generated by Django 4.2.29 on 2026-03-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval status for doctor account'),
        ),
    ]
