# Generated by Django 6.0.4 on 2026-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctorprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Public URL to profile photo', max_length=500),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Public URL to profile photo', max_length=500),
        ),
    ]
